LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := sdk_v8
LOCAL_SRC_FILES := android.jar
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_SUFFIX := $(COMMON_JAVA_PACKAGE_SUFFIX)
LOCAL_BUILT_MODULE_STEM := classes.jar
LOCAL_UNINSTALLABLE_MODULE := true

include $(BUILD_PREBUILT)
